name: Send Birthday Messages
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  send-birthday-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Send birthday messages
        run: |
          curl --location --request POST '${{ secrets.BASE_URL }}/api/birthday/send-messages' --data ''
